package com.user.jarvis

sealed class Command {
    data class OpenApp(val appName: String) : Command()
    data class SendMessage(val contactName: String, val text: String) : Command()
    data class CallContact(val contactName: String) : Command()
    data class SendWhatsApp(val contactName: String, val text: String) : Command()
    data class GoogleSearch(val query: String) : Command()
    data class PlaySong(val query: String) : Command()
    data class SetAlarm(val hour: Int, val minute: Int) : Command()
    data class SetReminder(val dayOffset: Int, val hour: Int, val minute: Int, val text: String, val isRecurring: Boolean = false) : Command()
    data class SaveNote(val text: String) : Command()
    data class AddTodo(val text: String) : Command()
    data class ChatReply(val text: String) : Command()
    data class WriteClipboard(val text: String) : Command()
    data class CreateContact(val name: String, val phone: String) : Command()
    object ReadTodos : Command()
    object ReadClipboard : Command()
    object ReadNotes : Command()
    object ShareNotes : Command()
    object ShareTodos : Command()
    object TellTime : Command()
    object TellBattery : Command()
    object VolumeUp : Command()
    object VolumeDown : Command()
    object FlashlightOn : Command()
    object FlashlightOff : Command()
    object OpenWifiSettings : Command()
    object OpenBluetoothSettings : Command()
    object SilentModeOn : Command()
    object SilentModeOff : Command()
    object LockPhone : Command()
    data class Unknown(val raw: String) : Command()
}
